### ISSUE TITLE
Projektdokumentation

### ISSUE THREAD

**Issue by freakimkaefig** [freakimkaefig/Music-XML-Analyzer#1]
Erstellen einer Projektdokumentation zur Abgabe

**Comment by freakimkaefig** [comment]
- [x] Kleinen Abschnitt über DomXPath einfügen (Lukas)  
  -- insb. auf Performance eingehen
- [x] Abschnitt zu Heroku-Hosting (Lukas)

**Comment by semmler1988** [comment]
soweit fertig, Digitaler Anhang muss noch befüllt werden

**Comment by led13714** [comment]
- [x] digitaler Anhang
- [x] final review
- [x] konsistente schriftgröße überprüfen
- [x] zu PDF konvertieren und abgeben

**Comment by semmler1988** [comment]
Punkt 3 Problemstellung, [...] intuitiv und die Auswertung ansprechend und verständnisvoll gestaltet werden.  "verständnisvoll" ersetzen durch "verständlich"

**Comment by semmler1988** [comment]
- [x] Punkt 3 Problemstellung, [...] intuitiv und die Auswertung ansprechend und verständnisvoll gestaltet werden.  "verständnisvoll" ersetzen durch "verständlich"
- [x] 4.4 suche nach patterns: doppeltes leerzeichen in "wird die maus zur     noteneingabe"
- [x] 5.1. projektablauf und zuständigkeiten: doppeltes leerzeichen bei der aufzählung der boards kurz vor dem ersten absatz
- [x] 5.3. Systemarchitektur: doppeltes Leerzeichen nach "wurde ein einfaches Datenbankschema entwickelt, welches in Abbildung 10 als ERM-Model...
- [x] Konsistente Schreibweise von "XPath" und "XQuery" überprüfen

**Comment by semmler1988** [comment]
Konsistente Schreibweise von "XPath" überprüfen
