### ISSUE TITLE
Center page-title in header. highlight for easy understanding.

### ISSUE THREAD

**Issue by led13714** [freakimkaefig/Music-XML-Analyzer#101]
momentan is jeder Page title so:

``` html
<div class="col-xs-12">
    <h1 class="text-center">Search</h1>
</div>
```

fänds denk ich geschickter, die im header zu zentrieren und bisl abzuheben vom header, dann hätte man z.b. auf der pattern-creation seite nich des problem, dass die add,delete und search button nich ganz angezeigt werden.

meinungen?

**Comment by semmler1988** [comment]
klingt vernünftig !

**Comment by matTailor** [comment]
jo kamma so macha!

**Comment by freakimkaefig** [comment]
fixed by: b71e8c6
