### ISSUE TITLE
ganze punktierte pause kann nicht gefunden werden

### ISSUE THREAD

**Issue by semmler1988** [freakimkaefig/Music-XML-Analyzer#105]
Eingeben kein Problem, gesucht wird aber nur die ganze Pause OHNE "punktiert"
![asdf](https://cloud.githubusercontent.com/assets/4980730/7023794/383f7116-dd38-11e4-9129-ee696e0c0615.PNG)
![asdfe](https://cloud.githubusercontent.com/assets/4980730/7023795/39b3be58-dd38-11e4-93fd-c2485d200fdb.PNG)

**Comment by freakimkaefig** [comment]
Hinzufügen von `dot`bei rests:

```
[{
    type: 1,
    notes: [
        {
            type: "note",
            pitch: {
                type: "half",
                dot: true,
                beam: false
            }
        },
        {
            type: "rest",
            duration: "whole"
            dot: true / false
        }
    ]
}]
```

bei mode: `rhythm` & `melody`

**Comment by matTailor** [comment]
dot added to note elements in pattern model
