### ISSUE TITLE
differences in visualization of rests in pattern and result extract (see screenshot)

### ISSUE THREAD

**Issue by led13714** [freakimkaefig/Music-XML-Analyzer#109]
![unbenannt](https://cloud.githubusercontent.com/assets/6040775/7043580/fdaa2196-ddea-11e4-96df-48baf5223cba.JPG)

**Comment by freakimkaefig** [comment]
kann für pattern  
`1x 1/64 rest dotted, 1x 1/16 rest`  
nix finden. auch nicht in dem test xml, des du geschickt hast.

**Comment by led13714** [comment]
fixed: 024cccbe30b3df97e4ee6e55042f34cd45f355d5
