### ISSUE TITLE
Fix Search Result Download

### ISSUE THREAD

**Issue by freakimkaefig** [freakimkaefig/Music-XML-Analyzer#114]
Download-Button not working.

**Comment by freakimkaefig** [comment]
Can't reproduce. Anyone?

**Comment by led13714** [comment]
reagarding pdfjs-download - probably an issue with safari browser, see:

https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#user-content-what-browsers-are-supported

which says "limited support" for safari

**Comment by freakimkaefig** [comment]
Manuels problem description:  

> wenn ich auf den Button „EXPORT AS PDF“ klicke kommt in der Konsole folgende Meldung: „Error: getJpegSize could not find the size of the image (jspdf.min.js, Zeile 63)“
> 
> Der Klick löst aber sonst keine Aktion aus.
> 
> Gerade habe ich durch Zufall entdeckt, dass es nach einem Page Refresh der Seite dann doch klappt … vllt. hilft das auch noch weiter.
> 
> Getestet auf Win 7, Aktueller Firefox

---

**Anybody with Win7 can reproduce this in Firefox?**

**Comment by freakimkaefig** [comment]
Test results:

:x: Win 8.1 - Safari 5.1.7 - localhost

> No need to support a browser from 2012 ?!?

---

:white_check_mark: Win 8.1 - Chrome 45.0.2427.7 dev-m (64-bit) - localhost
:white_check_mark: Win 8.1 - Chrome 45.0.2427.7 dev-m (64-bit) - heroku

:x:: Win 8.1 - Firefox 38.0.5 - localhost
:x: Win 8.1 - Firefox 38.0.5 - heroku

> Error: getJpegSize could not find the size of the image
> http://music-xml-analyzer.herokuapp.com/libs/jsPDF-0.9.0rc2/dist/jspdf.min.js
> Line 63

`.item .image` value is empty base64 image
![unbenannt](https://cloud.githubusercontent.com/assets/1469686/8145582/a9655dc4-120d-11e5-8b95-e85fda18a601.PNG)

**Comment by freakimkaefig** [comment]
Sometimes width gets NaN (not a number). Resolves after page refresh sometimes

Wrong:  
![unbenannt](https://cloud.githubusercontent.com/assets/1469686/8145728/30c18284-1213-11e5-83cd-756e93c3b890.PNG)

Right:  
![unbenannt](https://cloud.githubusercontent.com/assets/1469686/8145731/52aedafe-1213-11e5-9f8d-0527ea637c01.PNG)

**Comment by freakimkaefig** [comment]
Keep an eye on it, but i think i fixed it.
