### ISSUE TITLE
Score rendering on dashboard

### ISSUE THREAD

**Issue by freakimkaefig** [freakimkaefig/Music-XML-Analyzer#117]
Add ability to render complete score for song on dashboard  

Todos:
- [x] Create off-canvas section for score rendering
- [x] "Show score" button only when single file is selected
- [x] score rendering with ScoreController.php
- [x] score rendering with vexflow

**Comment by led13714** [comment]
+++possible UI concept:
create second (inactive by default) tab for score rendering.

+++another UI concept:
create button. button click shows score rendering overlay.

+++performance concept:
start score rendering as soon as d3 graphs are finished.

+++technical concept:
try re-using existing methods to fetch & create needed input for vexflow.

**Comment by freakimkaefig** [comment]
Interval distribution as bar chart (horizontal), pie charts to the right

off-canvas -> bootstrap (column break)

**Comment by freakimkaefig** [comment]
"Show score" on dashboard now opens new browser tab with score [d83b2ea]  

Deployed to heroku with hint "Beta".
