### ISSUE TITLE
Check polyphon pattern search

### ISSUE THREAD

**Issue by freakimkaefig** [freakimkaefig/Music-XML-Analyzer#119]
Only base note is searched??? notes with `<chord/>`-Tag ignored??

**Comment by freakimkaefig** [comment]
Result for search (sound sequence) d/4 d/4 in ActorPreludeSample.xml  
![unbenannt](https://cloud.githubusercontent.com/assets/1469686/8139703/070c1070-1156-11e5-9941-cc51bcb7fb1b.PNG)

**Comment by led13714** [comment]
yes <chord/> is ignored in soundsequence-, melody- and rhythm-search.
-> change?

**Comment by freakimkaefig** [comment]
ask manuel.burghardt@ur.de

**Comment by led13714** [comment]
well they have been removed for a good reason, see #95 and #99.
short version: 
- not possible to search for chords at the moment
- enabling chord notes leads to less results (no chord tag in pattern search vs chord tag in xml files)

--> only base notes are searched, which means sound sequences within chords are ignored 

**\* add note/hint about that somewhere?

**Comment by matTailor** [comment]
Maybe we could add a hint to get the users informed about not being able to search for chords

**Comment by semmler1988** [comment]
note/hint sounds like a good idea

**Comment by led13714** [comment]
added a hint on the results page (e0079aa41e9ef331e9babf6e268316fc32e208b6)

is that the way to go?

**Comment by freakimkaefig** [comment]
For now!
