### ISSUE TITLE
The website is not working

### ISSUE THREAD

**Issue by TariqYousef** [freakimkaefig/Music-XML-Analyzer#130]
the link is not working http://music-xml-analyzer.herokuapp.com/
and giving the following error message:

> Whoops, looks like something went wrong.

**Comment by freakimkaefig** [comment]
Sorry, the project is actually no longer maintained.

Feel free to fork the repository and use the code on your own hosting provider.
If i have some time left during the next weeks i maybe have a look at it.

**Comment by freakimkaefig** [comment]
Site should be running again.
An empty database caused the issue.
