### ISSUE TITLE
Cutted labels on bar charts

### ISSUE THREAD

**Issue by freakimkaefig** [freakimkaefig/Music-XML-Analyzer#47]
Bug on bar charts  

![unbenannt](https://cloud.githubusercontent.com/assets/1469686/6752245/1a3e12dc-cf0d-11e4-8330-5110734971cc.PNG)

**Comment by led13714** [comment]
has been fixxed already? (currently on search branch)

![unbenannt2](https://cloud.githubusercontent.com/assets/6040775/6755312/7f66f876-cf22-11e4-9c16-a08319205da6.JPG)
