### ISSUE TITLE
Wrong results

### ISSUE THREAD

**Issue by freakimkaefig** [freakimkaefig/Music-XML-Analyzer#72]
Search mode: Sound Sequence  
Pattern: B/5, B/5

Result: 3 mal gleiches Ergebnis, das aber kein b/5 enthält

![fledermaus](https://cloud.githubusercontent.com/assets/1469686/6866413/49e0508e-d478-11e4-9c99-517235295ec7.PNG)

XML-File: 
[Die_Fledermaus.xml | uploaded via ZenHub](https://files.zenhub.io/5515373ee954c4f02c66c31d)

//edit DAVE: erster treffer (start 752, end 754) stimmt. an position 753 ist halt ne "chord" note, sprich 752 und 753 is n akkord aus b/5 und d/6.

obiger screenshot ist mittlerweile veraltet, erstes result schaut jetz so aus (weil "chord"-tags, also zweite/dritte noten aus einem akkord, wie pausen ignoriert werden bei tonfolgen:
![unbenannt](https://cloud.githubusercontent.com/assets/6040775/6985020/f87bb064-da2e-11e4-811e-3bd3b873a28d.JPG)

problem scheint mir der $noteCounter aus dem ResultController.php zu sein, wenn ich mir die werte von "counter" der $noteObjects anschau (Zeile 225), siehe: 
![unbenannt](https://cloud.githubusercontent.com/assets/6040775/6985096/b5475338-da2f-11e4-99b9-e2bfe6db6ae3.JPG)

komisch schonmal, dass er angeblich bei 751 die erste note rot färbt, aber das tut er ja wohl nicht wirklich, da vor den rot markierten noten bereits b/5 und d/6 akkorde kommen. Da scheints nen unterschied zu geben im resultController.php zwischen tatsächlicher "notennummer" und deinem zähler. Die trefferpositionen die ich rauskriege stimmen mit der "notennummer" im xml file überein:

![unbenannt](https://cloud.githubusercontent.com/assets/6040775/6985137/5b243a32-da30-11e4-83b6-5c41045c224b.JPG)

//////EDIT DAVE:
Die Ergebnisse stimmen mittlerweile, die unteren xml files versuch ich zu testen, aber das carousel macht mir atm n strich durch die rechnung.... siehe #92

**Comment by freakimkaefig** [comment]
![ode_to_joy](https://cloud.githubusercontent.com/assets/1469686/6866663/f3ec8a00-d47a-11e4-8c88-4030a607dbbd.PNG)

XML-File:
[Ode_To_Joy_-_Beethoven_9th_.xml | uploaded via ZenHub](https://files.zenhub.io/55153bdce954c4f02c66c324)

**Comment by freakimkaefig** [comment]
Pattern: B/5, B/5

4 Ergebnisse, die das Pattern nicht enthalten (hab auch jeweils immer das XML untersucht)

XML-File:  
[Strauss_-_Tritsch-Tratsch_Polka_Piano.xml | uploaded via ZenHub](https://files.zenhub.io/55153ef7e954c4f02c66c327)

**Comment by led13714** [comment]
ohne zeilenangaben is des schwer nachvollziehbar wo genau b/5 b/5 sein solln... toller bugreport!

**Comment by freakimkaefig** [comment]
des is ja des problem. b/5 is in den results nicht drin
