### ISSUE TITLE
Midi JS: Rhythm is not correct (triplets, different durations)

### ISSUE THREAD

**Issue by matTailor** [freakimkaefig/Music-XML-Analyzer#74]

**Comment by led13714** [comment]
see #55

**Comment by led13714** [comment]
tempo (so halbwegs) und verhältnis der notenlängen stimmen.
letzte note klingt zu lange nach. 
(27.03.2015 15:36:52)@ create_pattern branch.

**Comment by led13714** [comment]
zwecks tempo:
                        // Laut Michl Standard bzw oft vorkommendes Metronom-'tempo' = 120
                        //  d.h. 120 schläge pro minute
                        // beats per minute ausgehend von 1/4 noten
                        // -> 120 viertel pro minute
                        // --> 30 ganze pro minute
                        // ---> 1 ganze = 2 sek.
                        // ----> timeout = (vorheriges) delay ( = notenlänge) \* 2000, da delay einer ganzen = 1 (siehe getDuration())

**Comment by led13714** [comment]
see #96

**Comment by matTailor** [comment]
duration fixed
