### ISSUE TITLE
Code cleaning

### ISSUE THREAD

**Issue by led13714** [freakimkaefig/Music-XML-Analyzer#76]

**Comment by freakimkaefig** [comment]
ggf methoden ordentlich kommentieren:  

## Javascript

```
/**
 * Method description
 *
 * @param {datatype}    name    description
 *
 * @return {datatype}    name    description
 */
bla123 = function(name) { ... }
```

http://en.wikipedia.org/wiki/JSDoc

---

## PHP

```
/**
 * Helper function to calculate the starting measures number
 *
 * @param   \DOMNode    $part     The \DOMNode element for the music xml part
 * @param   int         $start   The start notes number (inside the part)
 *
 * @return  int         Number of the measure where the extract should start
 *
 */
private function calculateStartExtract($part, $start) { ... }
```

http://de.wikipedia.org/wiki/PHPDoc
http://www.phpdoc.org/docs/latest/index.html

**Comment by led13714** [comment]
- [x] remove trailing whitespaces
- [x] remove unnessesary comments & logging
- [x] replace '!=' with '!==' if type comparission is needed (pretty much every where...)
  - [x] unnötig kompliziert jetz jedes mal nachzuschaun ob wert&type abgleich angebracht ist, da oftmals unklar ob z.B. boolesche werte tatsächlich vorliegen, oder ob true/false als String gesetzt....
- [x] einrückungen

**Comment by semmler1988** [comment]
cleaned dashboardView.js

**Comment by led13714** [comment]
-[ ] replace '!=' with '!==' if type comparission is needed (pretty much every where...)

**Comment by led13714** [comment]
- [ ] einrückungen

**Comment by led13714** [comment]
- [x] @ luggi: Result.php
- [x] @ luggi: Upload.php 
- [x] @ luggi: User.php
- [x] @ luggi: UploadController.php
- [x] @ luggi: HeaderView.js
- [x] @ luggi: finish/correct ResultView.js
- [x] @ luggi: finish/correct UploadView.js

**Comment by matTailor** [comment]
@luggi: am besten kommentierst du no die methoden beim dashboard model. Denke des kannst du besser erklären weistas ja a gmacht hast ;)

**Comment by matTailor** [comment]
patternModel & resultModel cleaned!

**Comment by led13714** [comment]
- [x] DashboardModel.js
- [x] UploadController.js
