### ISSUE TITLE
Exception handling displayed on frontend

### ISSUE THREAD

**Issue by freakimkaefig** [freakimkaefig/Music-XML-Analyzer#82]
How to get the error:  
- Uploaded files:
  - [BrookeWestSample.xml | uploaded via ZenHub](https://files.zenhub.io/551baf2ffad6476662f9a2f2)
  - [ActorPreludeSample.xml | uploaded via ZenHub](https://files.zenhub.io/551baf46fad6476662f9a2f3)
  - [DebuMandSample.xml | uploaded via ZenHub](https://files.zenhub.io/551baf4bfad6476662f9a2f4)
  - [Dichterliebe01.xml | uploaded via ZenHub](https://files.zenhub.io/551baf4ffad6476662f9a2f5)
  - [MahlFaGe4Sample.xml | uploaded via ZenHub](https://files.zenhub.io/551baf53fad6476662f9a2f6)
  - [MozaChloSample.xml | uploaded via ZenHub](https://files.zenhub.io/551baf5afad6476662f9a2f7)
  - [MozaVeilSample.xml | uploaded via ZenHub](https://files.zenhub.io/551baf60fad6476662f9a2f8)
  - [SchbAvMaSample.xml | uploaded via ZenHub](https://files.zenhub.io/551baf64fad6476662f9a2f9)
  - [Die_Fledermaus.xml | uploaded via ZenHub](https://files.zenhub.io/551baf6efad6476662f9a2fa)  
- Search for Pattern:

```
Mode: Melody
1/4 B5 + 1/4 B5
```
- Exception Division by zero

**Comment by led13714** [comment]
Exception no longer shown on frontend.
issue remaining open to fix 'division by zero'.

**Comment by led13714** [comment]
closed due to fix of calculation of rest durations; see 75475fc3e3f444a8d905fd37db5f126dfe0e544f
