### ISSUE TITLE
nearly no pattern is found in test triplets.xml

### ISSUE THREAD

**Issue by matTailor** [freakimkaefig/Music-XML-Analyzer#86]
Ich hab eine datei (testtriplets.xml) mit muse score erstellt. (Export funktion als xml)
Damit wollte ich midiJS auf der result seite testen.
Mir is allerdings aufgefallen dass ich fast keines der pattern (welche eig im xml laut musescore vorhanden sein sollten) finde.
Lediglich die 3 achtel triolen konnte ich bisher finden...
Is die datei vill unbrauchbar aus irg einem grund?
Funktioniert des bei euch?

**Comment by semmler1988** [comment]
![testxml](https://cloud.githubusercontent.com/assets/4980730/6966612/a7be4850-d95a-11e4-88b5-9396a76fe72a.png)
is ja auch nur eine triole mit 3 Achtel drin ?!?

**Comment by led13714** [comment]
als tonfolge find ich beliebige pattern in der datei. rhythm und melody müssen debugged werden...
denke tonfolge is soweit relativ gut und stabil.

**Comment by led13714** [comment]
fixxed (03.04.2015 17:21:45)
