### ISSUE TITLE
@doku ausblick/verbesserung: eingabe von akkorden; 

### ISSUE THREAD

**Issue by led13714** [freakimkaefig/Music-XML-Analyzer#93]

**Comment by led13714** [comment]
sprich die suche danach ermöglichen (wie triolen z.b.) und entsprechend auch die suche umgestalten.

**Comment by led13714** [comment]
see #99

**Comment by freakimkaefig** [comment]
Bei Akkorden ist ja im MusicXML die Note, die keinen `<chord>`-Tag hat die Grundnote eines Akkords (z.b. C-Dur Dreiklang, C - E - G). Macht also schon Sinn, nach der Grundnote zu suchen. wenn aber die Note iwo anders im Akkord (also mit `<chord>`-Tag kommt) eher weniger

**Comment by semmler1988** [comment]
ist eingebaut
