### ISSUE TITLE
multiple visualization errors @result caroussel for "1/4 rest 1/1 rest" in "ActorPreludeSample.xml"

### ISSUE THREAD

**Issue by led13714** [freakimkaefig/Music-XML-Analyzer#94]

**Comment by freakimkaefig** [comment]
After restructuring RhythmController.php, error in #98 occurs

**Comment by led13714** [comment]
error no longer occures, see fix for #98 still not visualized, see #92 (new comment)

**Comment by led13714** [comment]
rests now visualized, see e441e635f6f7b75ba94952ae67aaf63969571a98

new problem:
some carousell elements are empty!?
![unbenannt](https://cloud.githubusercontent.com/assets/6040775/7002716/85317b98-dc4f-11e4-88e2-49da2744cc83.JPG)

**Comment by freakimkaefig** [comment]
fixed by: 977a839

Resetting arrays on part change (Referencing: #98 )
