### ISSUE TITLE
RhythmSearch: Ignoring chords

### ISSUE THREAD

**Issue by freakimkaefig** [freakimkaefig/Music-XML-Analyzer#97]
Search rhythm 2 x 1/4

![unbenannt2](https://cloud.githubusercontent.com/assets/1469686/6992427/a18e305c-dacd-11e4-8de9-ff7aa0ee0222.PNG)

**Comment by led13714** [comment]
not a controller problem, rather a visualization one.

found results for 2x 1/4 in MozaVeilSamlpe.xml:
![unbenannt](https://cloud.githubusercontent.com/assets/6040775/6992609/8124cd02-dad8-11e4-8241-647988ab680e.JPG)

Takt 14 enthält nur ein Akkord, vorher und nachher sind keine  1/4 noten bzw 1/4 akkorde im xml.
angaben von startMeasureNumber, endMeasureNumber und xmlCounterArray stimmen mit der xml datei überein.

**Comment by freakimkaefig** [comment]
tempfix: fea22ff

**Comment by freakimkaefig** [comment]
Same file as above (only 1 result, with same pattern)

![unbenannt2](https://cloud.githubusercontent.com/assets/1469686/7020449/54245c08-dd19-11e4-8f4a-c15b2381d033.PNG)

**Comment by led13714** [comment]
fixed: 34c99a7fe3ed4909657ff2e70bb768ad01f51a48
