### ISSUE TITLE
Error in RhythmController.php

### ISSUE THREAD

**Issue by freakimkaefig** [freakimkaefig/Music-XML-Analyzer#98]
Search rhythm: 1x rest 1/4, 1x rest 1/1
Uploads: 
![unbenannt2](https://cloud.githubusercontent.com/assets/1469686/6992468/ba153cd0-dad0-11e4-9b0f-42784d5db006.PNG)

---

Error:
![unbenannt2](https://cloud.githubusercontent.com/assets/1469686/6992463/9fc9fd84-dad0-11e4-88da-166ebbac7d09.PNG)

**Comment by led13714** [comment]
problem tritt bei part wechsel P2 zu P3 auf:

``` xml
<note default-x="235">
<rest/>
<duration>8</duration>
<voice>1</voice>
<type>quarter</type>
</note>
</measure>
</part>
<!--
=========================================================
-->
<part id="P3">
<measure number="1" width="325">
<print>
<staff-layout number="1">
<staff-distance>84</staff-distance>
</staff-layout>
<measure-numbering>none</measure-numbering>
</print>
<attributes>
<divisions>8</divisions>
<key>
<fifths>0</fifths>
<mode>major</mode>
</key>
<time>
<beats>3</beats>
<beat-type>4</beat-type>
</time>
<clef>
<sign>G</sign>
<line>2</line>
</clef>
<staff-details>
<staff-size>108</staff-size>
</staff-details>
</attributes>
<note>
<rest measure="yes"/>
<duration>24</duration>
<voice>1</voice>
</note>
</measure>
```

die länge der zweiten pause wäre (24 / 8 / 4) eigentlich 0.75, dass spiegelt bei uns aber ne ganze wieder.

problem is nu also, dass er die startposition bereits im zweiten part sucht und die nich vorhanden ist.

**Comment by freakimkaefig** [comment]
Fixed by 977a839

Resetting arrays on part change
