### ISSUE TITLE
Inconsistency of chord results & visualization

### ISSUE THREAD

**Issue by led13714** [freakimkaefig/Music-XML-Analyzer#99]
soundsequence b/5 b/5:
![unbenannt](https://cloud.githubusercontent.com/assets/6040775/6996475/4044b988-db8b-11e4-9142-c6f85a98fa74.JPG)

Aktuell werden alle Noten die den "chord" tag enthalten im SoundSequenceController ignoriert. 
Die rote Markierung kommt zustande, weil die erste (=unterste) note eines Akkords nicht den "chord" tag enthält, sondern nur alle weiteren Noten eines Akkords.
Aus dem Grund werden auch die "b/5" in den Akkorden am Anfang der zweiten Notenzeile nicht als Ergebnis gewertet.

Soll das so bleiben? Warum?
Wenn wir Akkorde nicht ignorieren, müsste ich in obigen Beispiel nach b/5 und d/6 suchen, aber ohne das ich die Möglichkeit habe, tatsächlich nach Akkorden zu suchen...

Vorschläge?

**Comment by semmler1988** [comment]
jetz doch akkorde ?? hätt ma gedacht, wemmas ned suchen können, ignorieren wirs auch...?

**Comment by matTailor** [comment]
jo also nach akkorden kamma ja mit der pattern creation garnicht suchen.

**Comment by led13714** [comment]
Also akkorde raus aus suchergebnissen, da man sie ja nich suchen kann?

**Comment by semmler1988** [comment]
ja...scho eigentlich

**Comment by led13714** [comment]
see #93

**Comment by freakimkaefig** [comment]
Bei Akkorden ist ja im MusicXML die Note, die keinen `<chord>`-Tag hat die Grundnote eines Akkords (z.b. C-Dur Dreiklang, C - E - G). Macht also schon Sinn, nach der Grundnote zu suchen. wenn aber die Note iwo anders im Akkord (also mit `<chord>`-Tag kommt) eher weniger
